language: node_js
before_script:
  - npm install -g gatsby-cli gh-pages
  - cd ${TRAVIS_BUILD_DIR}/website/ && npm install
node_js:
  - "10"
script:
  - npm test
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
